-- Disable RLS sementara untuk testing
-- Script ini akan disable Row Level Security untuk semua tabel
-- HANYA UNTUK DEVELOPMENT/TESTING - JANGAN GUNAKAN DI PRODUCTION

-- Disable RLS untuk semua tabel
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE cars DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE wishlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE test_drives DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE chats DISABLE ROW LEVEL SECURITY;

-- Pesan konfirmasi
SELECT 'RLS disabled for all tables - FOR TESTING ONLY!' as status;